// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v5.29.3
// source: test/ts_proto_options.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const mixins: Extension<string[]> = {
  number: 50001,
  tag: 400010,
  repeated: true,
  packed: false,
  encode: (value: string[]): Uint8Array[] => {
    const encoded: Uint8Array[] = [];
    for (const v of value) {
      const writer = new BinaryWriter();
      writer.string(v);
      encoded.push(writer.finish());
    }
    return encoded;
  },
  decode: (tag: number, input: Uint8Array[]): string[] => {
    const values: string[] = [];
    for (const buffer of input) {
      const reader = new BinaryReader(buffer);
      values.push(reader.string());
    }

    return values;
  },
};

export interface Extension<T> {
  number: number;
  tag: number;
  singularTag?: number;
  encode?: (message: T) => Uint8Array[];
  decode?: (tag: number, input: Uint8Array[]) => T;
  repeated: boolean;
  packed: boolean;
}
